[package]
name = "init-rs"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# overkill-nvim = { path = "../neovim-rust/overkill-nvim/" }
overkill-nvim = { git = "https://github.com/turboladen/neovim-rust", branch = "feature/wrap-options" }

[profile.release]
lto = true
codegen-units = 1
