[package]
name = "init-rs"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# overkill_nvim = { path = "../overkill_nvim/overkill_nvim/" }
overkill_nvim = { git = "https://github.com/turboladen/overkill_nvim", branch = "feature/autocommands" }
nvim-oxi = { version = "0.2", features = ["neovim-0-8"] }
mlua = { version = "0.8", features = ["luajit", "module"] }

[profile.release]
lto = true
codegen-units = 1
