[package]
name = "nvim-rust-init"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
turducken-nvim = { path = "../neovim-rust/turducken-nvim//" }

[profile.release]
lto = true
codegen-units = 1
